### ISSUE TITLE
Could you provide a way to run with multiple GPUs?

### ISSUE THREAD

**Issue by FranciscoPark** [zhentingqi/rStar#21]
`CUDA_VISIBLE_DEVICES=0,1,2,3 python run_src/do_discriminate.py \
    --model_ckpt meta-llama/Llama-3.1-8B \
    --root_dir run_outputs/GSM8K/Llama-3.1-8B \
    --dataset_name GSM8K \
    --tensor_parallel_size 4 \
    --note tensor_parallelism`
    
    I am trying to modify the code a bit to use 4 GPUs with vllm tensor parallelism. However, I am keep getting 
```
    Final Accuracy: 0.0000
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/n3/jongyeon/rStar/run_src/do_discriminate.py", line 764, in <module>
[rank0]:     main()
[rank0]:   File "/home/n3/jongyeon/rStar/run_src/do_discriminate.py", line 518, in main
[rank0]:     "avg_num_candidates": total_num_candidates / num_tested,
[rank0]: ZeroDivisionError: division by zero
```

Is there a better way to run your code?

**Comment by LordEdison** [comment]
same problem😭
